### ISSUE TITLE
[BUG] Cannot list a secret created from the mobile app

### ISSUE THREAD

**Issue by Bastien-Satochip** [Tech-Aware/seedkeeper-tool#10]
Cannot list a secret that was created from the mobile app.

Here is the log: 

2024-08-13 12:46:09 - [exceptions.py:23] - ERROR - exceptions - __init__() - An error occurred in View
Traceback (most recent call last):
  File "view.py", line 2547, in _create_generic_secret_frame
  File "log_config.py", line 62, in wrapper
TypeError: _create_entry() got an unexpected keyword argument 'show'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "view.py", line 2302, in _show_secret_details
  File "log_config.py", line 62, in wrapper
  File "view.py", line 2555, in _create_generic_secret_frame
exceptions.UIElementError: Failed to create generic secret frame: _create_entry() got an unexpected keyword argument 'show'
Exception in Tkinter callback
Traceback (most recent call last):
  File "view.py", line 2547, in _create_generic_secret_frame
  File "log_config.py", line 62, in wrapper
TypeError: _create_entry() got an unexpected keyword argument 'show'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "view.py", line 2302, in _show_secret_details
  File "log_config.py", line 62, in wrapper
  File "view.py", line 2555, in _create_generic_secret_frame
exceptions.UIElementError: Failed to create generic secret frame: _create_entry() got an unexpected keyword argument 'show'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "tkinter\__init__.py", line 1702, in __call__
  File "customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
  File "view.py", line 2369, in <lambda>
  File "view.py", line 2310, in _show_secret_details
exceptions.SecretFrameCreationError: Error displaying secret details

And here is the screen of the app while trying to display the secret. 

![image](https://github.com/user-attachments/assets/d3a3c50b-bc12-495f-9afb-01b1452a15f2)

I can see the entry. But I cant have more info while clicking on the secret.

![image](https://github.com/user-attachments/assets/06b74410-4d97-4369-af98-a396dae592dd)

**Comment by Bastien-Satochip** [comment]
Note: this is not related to the mobile app... I just CANT display any mnemonic seedphrases already generated.

**Comment by Tech-Aware** [comment]
Normally @Bastien-Satochip  it wiil be good
