### ISSUE TITLE
[BUG] Cannot list a "2FA" secret

### ISSUE THREAD

**Issue by Bastien-Satochip** [Tech-Aware/seedkeeper-tool#13]
The 2FA secret is something that a user can create using the first version of the Seedkeeper-Tool (by Toporin).

![image](https://github.com/user-attachments/assets/71561043-d568-4d4b-8693-1eb5abebce04)
See line 3

Here, I try to display a 2FA secret and here is the output log. 

Even if this option will no longer be supported, I think we should allow the user to see it. 

2024-08-13 12:57:10 - [controller.py:358] - INFO - controller - retrieve_details_about_secret_selected() - 007 Retrieving details for secret ID: 3
2024-08-13 12:57:11 - [CardConnector.py:2073] - WARNING - pysatochip.CardConnector - seedkeeper_export_secret() - Export failed: export not allowed by SeedKeeper policy.
2024-08-13 12:57:11 - [controller.py:377] - ERROR - controller - retrieve_details_about_secret_selected() - 012 Error retrieving secret details: Export failed: export not allowed by SeedKeeper policy.
Traceback (most recent call last):
  File "controller.py", line 359, in retrieve_details_about_secret_selected
  File "pysatochip\CardConnector.py", line 2074, in seedkeeper_export_secret
pysatochip.CardConnector.SeedKeeperError: Export failed: export not allowed by SeedKeeper policy.
2024-08-13 12:57:11 - [exceptions.py:13] - ERROR - exceptions - __init__() - An error occurred in Seedkeeper Tool
Traceback (most recent call last):
  File "controller.py", line 359, in retrieve_details_about_secret_selected
  File "pysatochip\CardConnector.py", line 2074, in seedkeeper_export_secret
pysatochip.CardConnector.SeedKeeperError: Export failed: export not allowed by SeedKeeper policy.
2024-08-13 12:57:11 - [exceptions.py:23] - ERROR - exceptions - __init__() - An error occurred in View
Traceback (most recent call last):
  File "controller.py", line 359, in retrieve_details_about_secret_selected
  File "pysatochip\CardConnector.py", line 2074, in seedkeeper_export_secret
pysatochip.CardConnector.SeedKeeperError: Export failed: export not allowed by SeedKeeper policy.
2024-08-13 12:57:11 - [exceptions.py:163] - ERROR - exceptions - __init__() - An error occurred during secret retrieval
Traceback (most recent call last):
  File "controller.py", line 359, in retrieve_details_about_secret_selected
  File "pysatochip\CardConnector.py", line 2074, in seedkeeper_export_secret
pysatochip.CardConnector.SeedKeeperError: Export failed: export not allowed by SeedKeeper policy.
2024-08-13 12:57:11 - [log_config.py:70] - ERROR - controller - wrapper() - ! Exception in retrieve_details_about_secret_selected: 013 Failed to retrieve secret details: Export failed: export not allowed by SeedKeeper policy.
Traceback (most recent call last):
  File "controller.py", line 359, in retrieve_details_about_secret_selected
  File "pysatochip\CardConnector.py", line 2074, in seedkeeper_export_secret
pysatochip.CardConnector.SeedKeeperError: Export failed: export not allowed by SeedKeeper policy.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "log_config.py", line 62, in wrapper
  File "controller.py", line 378, in retrieve_details_about_secret_selected
exceptions.SecretRetrievalError: 013 Failed to retrieve secret details: Export failed: export not allowed by SeedKeeper policy.
2024-08-13 12:57:11 - [view.py:2309] - ERROR - view - _show_secret_details() - 013 Error displaying secret details: 013 Failed to retrieve secret details: Export failed: export not allowed by SeedKeeper policy.
Traceback (most recent call last):
  File "controller.py", line 359, in retrieve_details_about_secret_selected
  File "pysatochip\CardConnector.py", line 2074, in seedkeeper_export_secret
pysatochip.CardConnector.SeedKeeperError: Export failed: export not allowed by SeedKeeper policy.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "view.py", line 2288, in _show_secret_details
  File "log_config.py", line 62, in wrapper
  File "controller.py", line 378, in retrieve_details_about_secret_selected
exceptions.SecretRetrievalError: 013 Failed to retrieve secret details: Export failed: export not allowed by SeedKeeper policy.
2024-08-13 12:57:11 - [exceptions.py:13] - ERROR - exceptions - __init__() - An error occurred in Seedkeeper Tool
Traceback (most recent call last):
  File "controller.py", line 359, in retrieve_details_about_secret_selected
  File "pysatochip\CardConnector.py", line 2074, in seedkeeper_export_secret
pysatochip.CardConnector.SeedKeeperError: Export failed: export not allowed by SeedKeeper policy.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "view.py", line 2288, in _show_secret_details
  File "log_config.py", line 62, in wrapper
  File "controller.py", line 378, in retrieve_details_about_secret_selected
exceptions.SecretRetrievalError: 013 Failed to retrieve secret details: Export failed: export not allowed by SeedKeeper policy.
2024-08-13 12:57:11 - [exceptions.py:23] - ERROR - exceptions - __init__() - An error occurred in View
Traceback (most recent call last):
  File "controller.py", line 359, in retrieve_details_about_secret_selected
  File "pysatochip\CardConnector.py", line 2074, in seedkeeper_export_secret
pysatochip.CardConnector.SeedKeeperError: Export failed: export not allowed by SeedKeeper policy.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "view.py", line 2288, in _show_secret_details
  File "log_config.py", line 62, in wrapper
  File "controller.py", line 378, in retrieve_details_about_secret_selected
exceptions.SecretRetrievalError: 013 Failed to retrieve secret details: Export failed: export not allowed by SeedKeeper policy.
Exception in Tkinter callback
Traceback (most recent call last):
  File "controller.py", line 359, in retrieve_details_about_secret_selected
  File "pysatochip\CardConnector.py", line 2074, in seedkeeper_export_secret
pysatochip.CardConnector.SeedKeeperError: Export failed: export not allowed by SeedKeeper policy.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "view.py", line 2288, in _show_secret_details
  File "log_config.py", line 62, in wrapper
  File "controller.py", line 378, in retrieve_details_about_secret_selected
exceptions.SecretRetrievalError: 013 Failed to retrieve secret details: Export failed: export not allowed by SeedKeeper policy.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "tkinter\__init__.py", line 1702, in __call__
  File "customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
  File "view.py", line 2369, in <lambda>
  File "view.py", line 2310, in _show_secret_details
exceptions.SecretFrameCreationError: Error displaying secret details

**Comment by Tech-Aware** [comment]
@Bastien-Satochip 
I implemented it !! 

59fb488ee91f78bc224f966d5f73e5461b070e8b, 664e577e726f170e78e5504bd517924856ebe6e5
