### ISSUE TITLE
[Bug] My secrets - If the export type is set to "Encrypted only", the app throw an error.

### ISSUE THREAD

**Issue by Bastien-Satochip** [Tech-Aware/seedkeeper-tool#29]
On the current Seedkeeper-Tool application, you can specify how you want to export (to show it) a specific password, this is called "the export right".

Export right can be:
- Allow in plain text -> meaning the user will be able to see it in plain text
- Encrypted only -> meaning the password will be encrypted using a specifi authentikey

Both export right can co-exist. 

If you create - using the old application - a new secret with the following Export Right : Encrypted only. When you want to see it on the new Seedkeeper application, there is an error.

```
2024-09-02 15:08:21 - [CardConnector.py:2073] - WARNING - pysatochip.CardConnector - seedkeeper_export_secret() - Export failed: export not allowed by SeedKeeper policy.
2024-09-02 15:08:21 - [controller.py:433] - ERROR - controller - retrieve_details_about_secret_selected() - 012 Error retrieving secret details: Export failed: export not allowed by SeedKeeper policy.
Traceback (most recent call last):
  File "controller.py", line 415, in retrieve_details_about_secret_selected
  File "pysatochip\CardConnector.py", line 2074, in seedkeeper_export_secret
pysatochip.CardConnector.SeedKeeperError: Export failed: export not allowed by SeedKeeper policy.
2024-09-02 15:08:21 - [exceptions.py:13] - ERROR - exceptions - __init__() - An error occurred in Seedkeeper Tool
Traceback (most recent call last):
  File "controller.py", line 415, in retrieve_details_about_secret_selected
  File "pysatochip\CardConnector.py", line 2074, in seedkeeper_export_secret
pysatochip.CardConnector.SeedKeeperError: Export failed: export not allowed by SeedKeeper policy.
2024-09-02 15:08:21 - [exceptions.py:23] - ERROR - exceptions - __init__() - An error occurred in View
Traceback (most recent call last):
  File "controller.py", line 415, in retrieve_details_about_secret_selected
  File "pysatochip\CardConnector.py", line 2074, in seedkeeper_export_secret
pysatochip.CardConnector.SeedKeeperError: Export failed: export not allowed by SeedKeeper policy.
2024-09-02 15:08:21 - [exceptions.py:163] - ERROR - exceptions - __init__() - An error occurred during secret retrieval
Traceback (most recent call last):
  File "controller.py", line 415, in retrieve_details_about_secret_selected
  File "pysatochip\CardConnector.py", line 2074, in seedkeeper_export_secret
pysatochip.CardConnector.SeedKeeperError: Export failed: export not allowed by SeedKeeper policy.
2024-09-02 15:08:21 - [log_config.py:70] - ERROR - controller - wrapper() - ! Exception in retrieve_details_about_secret_selected: 013 Failed to retrieve secret details: Export failed: export not allowed by SeedKeeper policy.
Traceback (most recent call last):
  File "controller.py", line 415, in retrieve_details_about_secret_selected
  File "pysatochip\CardConnector.py", line 2074, in seedkeeper_export_secret
pysatochip.CardConnector.SeedKeeperError: Export failed: export not allowed by SeedKeeper policy.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "log_config.py", line 62, in wrapper
  File "controller.py", line 434, in retrieve_details_about_secret_selected
exceptions.SecretRetrievalError: 013 Failed to retrieve secret details: Export failed: export not allowed by SeedKeeper policy.
2024-09-02 15:08:21 - [view.py:2350] - ERROR - view - _show_secret_details() - 013 Error displaying secret details: 013 Failed to retrieve secret details: Export failed: export not allowed by SeedKeeper policy.
Traceback (most recent call last):
  File "controller.py", line 415, in retrieve_details_about_secret_selected
  File "pysatochip\CardConnector.py", line 2074, in seedkeeper_export_secret
pysatochip.CardConnector.SeedKeeperError: Export failed: export not allowed by SeedKeeper policy.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "view.py", line 2327, in _show_secret_details
  File "log_config.py", line 62, in wrapper
  File "controller.py", line 434, in retrieve_details_about_secret_selected
exceptions.SecretRetrievalError: 013 Failed to retrieve secret details: Export failed: export not allowed by SeedKeeper policy.
2024-09-02 15:08:21 - [exceptions.py:13] - ERROR - exceptions - __init__() - An error occurred in Seedkeeper Tool
Traceback (most recent call last):
  File "controller.py", line 415, in retrieve_details_about_secret_selected
  File "pysatochip\CardConnector.py", line 2074, in seedkeeper_export_secret
pysatochip.CardConnector.SeedKeeperError: Export failed: export not allowed by SeedKeeper policy.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "view.py", line 2327, in _show_secret_details
  File "log_config.py", line 62, in wrapper
  File "controller.py", line 434, in retrieve_details_about_secret_selected
exceptions.SecretRetrievalError: 013 Failed to retrieve secret details: Export failed: export not allowed by SeedKeeper policy.
2024-09-02 15:08:21 - [exceptions.py:23] - ERROR - exceptions - __init__() - An error occurred in View
Traceback (most recent call last):
  File "controller.py", line 415, in retrieve_details_about_secret_selected
  File "pysatochip\CardConnector.py", line 2074, in seedkeeper_export_secret
pysatochip.CardConnector.SeedKeeperError: Export failed: export not allowed by SeedKeeper policy.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "view.py", line 2327, in _show_secret_details
  File "log_config.py", line 62, in wrapper
  File "controller.py", line 434, in retrieve_details_about_secret_selected
exceptions.SecretRetrievalError: 013 Failed to retrieve secret details: Export failed: export not allowed by SeedKeeper policy.
Exception in Tkinter callback
Traceback (most recent call last):
  File "controller.py", line 415, in retrieve_details_about_secret_selected
  File "pysatochip\CardConnector.py", line 2074, in seedkeeper_export_secret
pysatochip.CardConnector.SeedKeeperError: Export failed: export not allowed by SeedKeeper policy.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "view.py", line 2327, in _show_secret_details
  File "log_config.py", line 62, in wrapper
  File "controller.py", line 434, in retrieve_details_about_secret_selected
exceptions.SecretRetrievalError: 013 Failed to retrieve secret details: Export failed: export not allowed by SeedKeeper policy.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "tkinter\__init__.py", line 1702, in __call__
  File "customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
  File "view.py", line 2409, in <lambda>
  File "view.py", line 2351, in _show_secret_details
exceptions.SecretFrameCreationError: Error displaying secret details
```
![image](https://github.com/user-attachments/assets/1e20a6d7-d920-4bfc-847f-a7e921635692)

**Comment by Bastien-Satochip** [comment]
The expected behavior should be to show: 
- the Label
and a message saying "You cannot see this secret in plaintext."

**Comment by Tech-Aware** [comment]
Hi @Bastien-Satochip 

I encounter a problem with this issue. I cant export a secret that is secure_export for seedkeeper policy.
Then, as the pysatochip library manage export raising specific error for policy i cant retrieved a secret without provide sid_pubkey. But i dont have this pub_key ! 

2024-09-05 15:05:47 - [CardConnector.py:2073] - WARNING - pysatochip.CardConnector - seedkeeper_export_secret() - Export failed: export not allowed by SeedKeeper policy.

The consequence is that i cant retrieve only the label neither ! And then i cant generate frame with details. 

maybe showing popup and go back to secret list ?

**Comment by Tech-Aware** [comment]
It was a good challenge @Bastien-Satochip 
Hope i did it well : [c704baf..86ad81a](https://github.com/Tech-Aware/seedkeeper-tool/commit/86ad81ac1d25bf02925437cb9195bdfb53c54157)

https://github.com/user-attachments/assets/1a51754f-abd6-44d3-ab7a-10897ab06ce1
