### ISSUE TITLE
[Bug] When you start the application and no card is put in the reader

### ISSUE THREAD

**Issue by Bastien-Satochip** [Tech-Aware/seedkeeper-tool#33]
If you start the application and no card is put on the reader - if you click on "Let's go", you encounter some troubles

So here, I will click on "Let's go" but no card is connected to the computer.
![image](https://github.com/user-attachments/assets/c204e660-37d5-49e6-b67f-d8853e6a3d7f)

I have this pop-up: 
![image](https://github.com/user-attachments/assets/c11fbcc3-83a3-4635-8194-4c1822e13dd2)

The normal behavior should be: "No card connected"

If I put a PIN code, I have these pop up
![image](https://github.com/user-attachments/assets/360726eb-e50f-4328-b118-f5c1c6749d67)
![image](https://github.com/user-attachments/assets/5fde7f67-4bcc-4eb6-a1ea-2a4433e01fcc)

Could you check it?

Here are the logs: 

```
2024-09-02 15:34:29 - [controller.py:115] - INFO - controller - card_setup_native_pin() - 003 Sending setup native PIN command to card
2024-09-02 15:34:29 - [controller.py:137] - ERROR - controller - card_setup_native_pin() - 007 Unexpected error in card_setup_native_pin: No card found! Please insert card!
Traceback (most recent call last):
  File "controller.py", line 120, in card_setup_native_pin
  File "pysatochip\CardConnector.py", line 544, in card_setup
  File "pysatochip\CardConnector.py", line 252, in card_transmit
pysatochip.CardConnector.CardNotPresentError: No card found! Please insert card!
2024-09-02 15:34:29 - [view.py:1459] - INFO - view - show() - 001 Showing popup: ERROR
2024-09-02 15:34:29 - [view.py:1540] - SUCCESS - view - show() - 016 Popup 'ERROR' displayed successfully
2024-09-02 15:34:29 - [exceptions.py:13] - ERROR - exceptions - __init__() - An error occurred in Seedkeeper Tool
Traceback (most recent call last):
  File "controller.py", line 120, in card_setup_native_pin
  File "pysatochip\CardConnector.py", line 544, in card_setup
  File "pysatochip\CardConnector.py", line 252, in card_transmit
pysatochip.CardConnector.CardNotPresentError: No card found! Please insert card!
2024-09-02 15:34:29 - [exceptions.py:123] - ERROR - exceptions - __init__() - An error occurred in Controller
Traceback (most recent call last):
  File "controller.py", line 120, in card_setup_native_pin
  File "pysatochip\CardConnector.py", line 544, in card_setup
  File "pysatochip\CardConnector.py", line 252, in card_transmit
pysatochip.CardConnector.CardNotPresentError: No card found! Please insert card!
2024-09-02 15:34:29 - [log_config.py:70] - ERROR - controller - wrapper() - ! Exception in card_setup_native_pin: 008 Failed to set up native PIN: No card found! Please insert card!
Traceback (most recent call last):
  File "controller.py", line 120, in card_setup_native_pin
  File "pysatochip\CardConnector.py", line 544, in card_setup
  File "pysatochip\CardConnector.py", line 252, in card_transmit
pysatochip.CardConnector.CardNotPresentError: No card found! Please insert card!

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "log_config.py", line 62, in wrapper
  File "controller.py", line 140, in card_setup_native_pin
exceptions.ControllerError: 008 Failed to set up native PIN: No card found! Please insert card!
```

**Comment by Tech-Aware** [comment]
I will make teh same things as satochip-utils, locking menu_element but not locking app access
