### ISSUE TITLE
[Bug] When the export right is set to "Encrypted only", the app bug

### ISSUE THREAD

**Issue by Bastien-Satochip** [Tech-Aware/seedkeeper-tool#41]
I have a few secrets on my Seedkeeper that cannot be exported in plain text. 
These secrets were generated from the old Seedkeeper desktop tool with the parameter:
- Export_Right=Encrypted only

You closed this bug in https://github.com/Tech-Aware/seedkeeper-tool/commit/86ad81ac1d25bf02925437cb9195bdfb53c54157
But now it happens again. 

Could you check it.? 

Here is the stack trace: 
2024-09-26 11:06:52 - [view.py:1001] - SUCCESS - view - create_seedkeeper_menu() - 004 Seedkeeper menu created and placed successfully
2024-09-26 11:06:52 - [view.py:2788] - ERROR - view - _show_secret_details() - 013 Error displaying secret details: 'subtype'
Traceback (most recent call last):
  File "view.py", line 2751, in _show_secret_details
KeyError: 'subtype'
2024-09-26 11:06:52 - [exceptions.py:13] - ERROR - exceptions - __init__() - An error occurred in Seedkeeper Tool
Traceback (most recent call last):
  File "view.py", line 2751, in _show_secret_details
KeyError: 'subtype'
2024-09-26 11:06:52 - [exceptions.py:23] - ERROR - exceptions - __init__() - An error occurred in View
Traceback (most recent call last):
  File "view.py", line 2751, in _show_secret_details
KeyError: 'subtype'
Exception in Tkinter callback
Traceback (most recent call last):
  File "view.py", line 2751, in _show_secret_details
KeyError: 'subtype'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "tkinter\__init__.py", line 1702, in __call__
  File "customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
  File "view.py", line 2852, in <lambda>
  File "view.py", line 2789, in _show_secret_details
exceptions.SecretFrameCreationError: Error displaying secret details

**Comment by Tech-Aware** [comment]
@Bastien-Satochip 
could you say me which type of secret are concerned about this please ? it's to test !
