### ISSUE TITLE
[Bug] Cannot import a seedphrase

### ISSUE THREAD

**Issue by Bastien-Satochip** [Tech-Aware/seedkeeper-tool#6]
Impossible to import an existing seedphrase.
To reproduce what I'm doing: 
- Click on "Import"
- Put a label like: Test account with a few ETH
- Select 12 words
- Past the seedphrase
- Hit the "Save on card" button

Error:
![image](https://github.com/user-attachments/assets/626944c4-5150-4a5b-b52c-af03e014cdbe)

**Comment by Bastien-Satochip** [comment]
Here is the logfile: 

2024-08-13 12:36:22 - [view.py:3210] - INFO - view - _save_mnemonic_to_import_on_card() - 019 Saving mnemonic to card
2024-08-13 12:36:22 - [controller.py:398] - INFO - controller - import_seed() - 001 Importing seed
2024-08-13 12:36:22 - [controller.py:401] - INFO - controller - import_seed() - 002 Imported seed is valid
2024-08-13 12:36:22 - [controller.py:410] - ERROR - controller - import_seed() - 005 Error importing seed: String value expected
Traceback (most recent call last):
  File "controller.py", line 402, in import_seed
  File "mnemonic\mnemonic.py", line 235, in to_seed
  File "mnemonic\mnemonic.py", line 100, in normalize_string
TypeError: String value expected
2024-08-13 12:36:22 - [view.py:1392] - INFO - view - show() - 001 Showing popup: ERROR
2024-08-13 12:36:22 - [view.py:1430] - WARNING - view - add_content() - 008 Icon file not found: ./pictures_db/icon_seed_popup.jpg
2024-08-13 12:36:22 - [view.py:1473] - SUCCESS - view - show() - 016 Popup 'ERROR' displayed successfully
2024-08-13 12:36:22 - [view.py:3218] - SUCCESS - view - _save_mnemonic_to_import_on_card() - 021 Mnemonic without passphrase saved to card successfully

**Comment by Bastien-Satochip** [comment]
Despite this line: 2024-08-13 12:36:22 - [view.py:3218] - SUCCESS - view - _save_mnemonic_to_import_on_card() - 021 Mnemonic without passphrase saved to card successfully

There is no pop up saying OK and no seedphrase stored inside the Seedkeeper.

**Comment by Tech-Aware** [comment]
It's ok @Bastien-Satochip 
c074bec771ac977b11a57d0cb0e42af3f0f0c9c0
